Use debugpy only when DEBUGPY is defined
To avoid
RuntimeError: Can't listen for client connections: [Errno 98] Address already in use
when another celery command is run (like in the liveness probe)