Use packit-service's Mixins
Some properties moved from Handler to these mixins with
https://github.com/packit/packit-service/commit/bf1b977f37b6f21bb083983db42884034dbf9dd1

Fixes
TypeError: Can't instantiate abstract class DistGitMRHandler with abstract methods clean_api, packit_api, project, project_url, service_config